---
- hosts: vms
  gather_facts: False
  tasks:
    - set_fact:
        hypervisor: "{{groups['hypervisor']|random}}"

    - name: template VM definition
      delegate_to: "{{ hypervisor }}"
      template: src=dom.xml.j2 dest=/tmp/{{inventory_hostname}}-tpl.xml

    - name: VM definition
      delegate_to: "{{ hypervisor }}"
      virt_domain:
        name: "{{ inventory_hostname}}"
        state: latest
        xml: "{{ lookup('template','dom.xml.j2') }}"
      register: out
      # FIXME: model = Haswell ignore

    - debug: msg="{{out.tree}}"

#    - name: write xmls
#      delegate_to: "{{ hypervisor }}"
#      copy:
#        content: "{{item.value}}"
#        dest: /tmp/{{inventory_hostname}}-{{item.key}}.xml
#      with_dict: "{{ {'current': out.current_xml, 'defined': out.defined_xml} }}"
